"""empty message

Revision ID: 6b4cb8571e42
Revises: 762402052503
Create Date: 2021-03-02 18:30:52.787430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b4cb8571e42'
down_revision = '762402052503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(length=180), nullable=True),
    sa.Column('estatura', sa.String(length=180), nullable=True),
    sa.Column('genero', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('poblacion', sa.Integer(), nullable=True),
    sa.Column('diametro', sa.Integer(), nullable=True),
    sa.Column('gravedad', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('personajes_name', sa.String(length=200), nullable=True),
    sa.Column('planetas_name', sa.String(length=200), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['personajes_name'], ['personajes.name'], ),
    sa.ForeignKeyConstraint(['planetas_name'], ['planetas.name'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('user', sa.Column('contraseña', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('genero', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=250), nullable=False))
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'name')
    op.drop_column('user', 'genero')
    op.drop_column('user', 'contraseña')
    op.drop_table('favoritos')
    op.drop_table('planetas')
    op.drop_table('personajes')
    # ### end Alembic commands ###
